# Generated by Django 4.0.2 on 2022-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Calculate_BMI',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Height',
        ),
        migrations.AddField(
            model_name='user',
            name='BMI_Calculate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Weight',
            field=models.FloatField(default=0),
        ),
    ]
